name: Create Builder image with Graalvm-ce and native-image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image 20.3
      run: docker build src/20.3 --file Dockerfile --tag cloud-surfers/graalvm-builder:20.3-$(date +%s)
    - name: Build the Docker image 20.2
      run: docker build src/20.2 --file Dockerfile --tag cloud-surfers/graalvm-builder:20.2-$(date +%s)
